[project]
name = "HeraCLIs"
version = "0.1.0"
description = "Simple rep logger"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "rich",
    "click",
]

[project.scripts]
hw = "heraclis.hw:cli"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
